apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bison-go 
  janus-idp.io/tekton: bison-go
  backstage.io/kubernetes-id: bison-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bison-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  